### ISSUE TITLE
Focus input box on website load

### ISSUE THREAD

**Issue by olfMombach** [mozq/dencode-web#10]
Hello,
when loading the site the central input box is not focused. For people that heavily use the keyboard and shortcuts, manually selecting the box using the mouse is an additional step. Therefore I would suggest using the [HTMLElement.focus()](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus) method in Javascript or similar to make the browser focus the element after loading the website, requiring no additional mouse input.

The approach I was thinking of would be something like

~~~ javascript
document.addEventListener("DOMContentLoaded", function() {
            let textBox = document.getElementById("v");  // in some way get the text box
            textBox.focus();
});
~~~

**Comment by mozq** [comment]
@olfMombach,
This change has been deployed to https://dencode.com/ .

I remembered that I had removed this feature in the past because the software keyboard is displayed on mobile devices.
When I try it on my iPhone, there seems to be no problem at the moment, but I might add a condition regarding whether it is a mobile device or not.

Please let me know if you have any good solution.

**Comment by mozq** [comment]
@olfMombach,
Fixed to focus only on non-touch devices. This change has been deployed to https://dencode.com/ .

**Comment by olfMombach** [comment]
Good solution with the mobile detection, works well on my Laptop. Thanks for the enhancement.
